export const GET_EMAIL_GUESS_STARTED = "GET_EMAIL_GUESS_STARTED";
export const GET_EMAIL_GUESS_SUCCESS = "GET_EMAIL_GUESS_SUCCESS";
export const GET_EMAIL_GUESSS_FAILURE = "GET_EMAIL_GUESSS_FAILURE";
